import os
import random
import sys
from pathlib import Path


def setup_django():
    project_root = Path(__file__).resolve().parents[1]
    backend_dir = project_root / "backend"
    sys.path.insert(0, str(backend_dir))
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

    import django

    django.setup()


def run():
    from orders.models import Customer, IntakeMessage, Order, OrderItem, OrderStatusHistory

    statuses = [
        Order.Status.NEW,
        Order.Status.NEEDS_INFO,
        Order.Status.CONFIRMED,
        Order.Status.IN_PROGRESS,
        Order.Status.SHIPPED,
        Order.Status.DELIVERED,
        Order.Status.CANCELLED,
    ]
    channels = [IntakeMessage.Channel.TELEGRAM, IntakeMessage.Channel.WEB, IntakeMessage.Channel.EMAIL]
    products = ["кружка", "футболка", "худи", "термос", "стикеры"]
    cities = ["Москва", "Санкт-Петербург", "Казань", "Новосибирск"]

    created = 0
    for i in range(1, 21):
        customer = Customer.objects.create(
            name=f"Demo Customer {i}",
            phone=f"+7903000{i:04d}",
            email=f"demo{i}@example.com",
        )
        channel = random.choice(channels)
        intake = IntakeMessage.objects.create(
            channel=channel,
            raw_text=f"Тестовый заказ #{i}",
            customer=customer,
            idempotency_key=f"seed_{channel}_{i}",
            metadata={"seed": True},
        )
        status = random.choice(statuses)
        order = Order.objects.create(
            customer=customer,
            intake=intake,
            channel=channel,
            status=status,
            delivery_address=f"{random.choice(cities)}, улица Пример {i}",
            delivery_city=random.choice(cities),
            is_paid=random.choice([True, False]),
            total_amount=random.randint(500, 7000),
        )
        OrderItem.objects.create(
            order=order,
            title=random.choice(products),
            quantity=random.randint(1, 4),
        )
        OrderStatusHistory.objects.create(
            order=order,
            old_status="",
            new_status=status,
            changed_by="seed_script",
            comment="generated by seed_data.py",
        )
        created += 1

    print(f"Seed completed. Orders created: {created}")


if __name__ == "__main__":
    setup_django()
    run()
